baseURL = 'https://lisenhatson.github.io/siteproj'
languageCode = 'en-us'
title = 'Lisenapati'
theme = 'etlise'

[params]
  favicon = "favicon.png"

[menu]

  [[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 1

 [[menu.main]]
    name = "Links"
    url = "/links"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/about"
    weight = 10

  [[menu.social]]
    name = "GitHub"
    pre = "github"
    url = "https://github.com/LisenHatson"
    weight = 10

  [[menu.social]]
    name = "RSS Feed"
    pre = "rss"
    url = "/index.xml"
    weight = 30


[markup]
  [markup.goldmark.parser]
    wrapStandAloneImageWithinParagraph = false
  [markup.highlight]
    style = 'evergarden'
